#cloud-config
users:
  - name: locadmin
    groups: sudo
    shell: /bin/bash
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAu5o4mTP7UVrAIvA199fSN1t1ea8QS+ECXlhBNftfR3 locadmin