#cloud-config
users:
  - name: locadmin
    groups: sudo
    shell: /bin/bash
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 /aZoENqVcQIZLm3Mdb1Ibr5UpBdvsEaqWzp locadmin
