@startuml fotocasa_lead_integration
!theme cerulean-outline
 
participant "kodit-backoffice" as backoffice
participant "kodit-proxy" as proxy
participant "kodit-service" as service
participant "kodit-auth" as auth
database "postgres" as postgres
database "redis" as redis
 
autonumber
autoactivate off
 
skinparam style strictuml
skinparam responseMessageBelowArrow true
skinparam maxMessageSize 250
skinparam backgroundColor white
skinparam DefaultFontName SansSerif
 
title Authentication

backoffice -> proxy: /api/kodit-service
proxy -> service: /api/kodit-service
service -> service: init sensitive function
service -> auth: check permission
auth -> service: api call allowed
service -> service: complete sensitive function
service --> service: response

@enduml