@startuml fotocasa_lead_integration
!theme cerulean-outline
 
participant "backoffice" as backoffice
participant "proxy" as proxy
participant "auth" as auth
participant "google-workspace-sdk" as workspace

 
autonumber
autoactivate off
 
skinparam style strictuml
skinparam responseMessageBelowArrow true
skinparam maxMessageSize 250
skinparam backgroundColor white
skinparam DefaultFontName SansSerif
 
title Authentication

backoffice -> proxy: auth/

@enduml