@startuml fotocasa_lead_integration
!theme cerulean-outline
 
participant "backoffice" as backoffice
participant "proxy" as proxy
participant "service" as service
participant "auth" as auth
database "postgres" as postgres
database "redis" as redis
 
autonumber
autoactivate off
 
skinparam style strictuml
skinparam responseMessageBelowArrow true
skinparam maxMessageSize 250
skinparam backgroundColor white
skinparam DefaultFontName SansSerif
 
title Authentication

backoffice -> proxy: /api/service
proxy -> service: /api/service
service -> service: init sensitive function
service -> auth: check permission
auth -> service: api call allowed
service -> service: complete sensitive function
service --> service: response

@enduml